services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Rfuehricht\Configloader\:
    resource: '../Classes/*'
    autowire: true
    public: true

  Rfuehricht\Configloader\EventListener\CacheFlushListener:
    tags:
      - name: event.listener
        identifier: 'theme/clear-configuration-cache'

  Rfuehricht\Configloader\EventListener\GetConfigListener:
    tags:
      - name: event.listener
        identifier: 'configloader/evaluate-getconfig-function'
